### ISSUE TITLE
#fix database sql not working

### ISSUE THREAD

**Issue by tahajuda90** [Klodovskyy/BoostZone#1]
while i want to, excute sql file all tables missing

**Comment by tahajuda90** [comment]
fix

**Comment by Klodovsky** [comment]
Please follow the steps in .readme

**Comment by tahajuda90** [comment]
I was follow but when I access into login it's error 404

**Comment by Klodovsky** [comment]
Here's my email : khaled.benhassen@polytechnicien.tn 

Send me a mail there and we will arrange screen sharing and I'll help you fix this from there
